export const proposalSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "proposalId",
    "title",
    "summary",
    "learningObjective",
    "agentSummary",
    "phrases",
    "safetyReview",
    "aiLiteracyConnections",
    "parentExplanation",
    "approvalQuestion",
    "provenance",
  ],
  properties: {
    proposalId: { type: "string" },
    title: { type: "string" },
    summary: { type: "string" },
    learningObjective: { type: "string" },
    agentSummary: { type: "string" },
    phrases: {
      type: "array",
      minItems: 3,
      maxItems: 6,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "name",
          "counts",
          "movement",
          "transition",
          "musicCue",
          "teachingCue",
          "computationalIdea",
        ],
        properties: {
          name: { type: "string" },
          counts: { type: "string" },
          movement: { type: "string" },
          transition: { type: "string" },
          musicCue: { type: "string" },
          teachingCue: { type: "string" },
          computationalIdea: { type: "string" },
        },
      },
    },
    safetyReview: {
      type: "object",
      additionalProperties: false,
      required: ["status", "flags", "notes"],
      properties: {
        status: { type: "string", enum: ["CLEAR", "REVIEW_REQUIRED", "HOLD"] },
        flags: { type: "array", items: { type: "string" } },
        notes: { type: "array", items: { type: "string" } },
      },
    },
    aiLiteracyConnections: {
      type: "array",
      minItems: 2,
      maxItems: 5,
      items: { type: "string" },
    },
    parentExplanation: { type: "string" },
    approvalQuestion: { type: "string" },
    provenance: {
      type: "object",
      additionalProperties: false,
      required: ["sourceMoves", "assumptions", "humanDecisionRequired"],
      properties: {
        sourceMoves: { type: "array", items: { type: "string" } },
        assumptions: { type: "array", items: { type: "string" } },
        humanDecisionRequired: { type: "boolean" },
      },
    },
  },
};
